== RSQL-QUERYDSL MILESTONES

=== 3.0.0

=== JPA
1. NICE TO HAVE : Join is dependent on other rql components like select, filter, sort. Therefore JOIN repeats rql path navigation to collect all paths involve.
   Creates a modular and yet extensible integrations.

2. NEED : support aggregation and groupby +
   Considerations: +
   * single table aggregation only allows grouping on the same aggregated table column
   * aggregation requires HAVING and not WHERE
   * aggregation don't allow select on other columns of the parent table

3. NICE TO HAVE : Module that implements runtime-generated default PATH and JOIN Mapping, from parent QClass.
   Use caching for performance.
   Considerations: +
   * How to walk QClass and extract metadata

=== MONGODB
1. NEED : DBRef Support, must use join-on instead of where for DBRef fields. Both FILTER and JOIN Visitors are affected.
2. NEED : Separate mongodb from jpa modules

=== GENERAL
1. NEED : Externalized DateTime Format
2. NICE TO HAVE : RHS path support
3. NEED : Use DSL as API with internal Factory or Registry to automatically provide the parsers based on target database e.g. JPA, Mongo


=== TASKS
==== 3.0.0-M1
MONGODB.2
GENERAL.3
MONGODB.1

==== 3.0.0-M2
GENERAL.1
????

==== 3.0.0-M3
release each major jar as bundled