= RSQL-QueryDSL 

Author : John Michael Vincent S. Rustia +


ifdef::env-github[]
image:https://api.travis-ci.org/vineey/archelix-rsql.svg?token%2FkdSmFoN3e8GGHqffx761["Build Status", link="https://travis-ci.org/vineey/archelix-rsql"]
image:http://img.shields.io/:license-mit-blue.svg["License", link="https://github.com/vineey/archelix-rsql/blob/master/LICENSE.md"]
image:https://coveralls.io/repos/github/vineey/archelix-rsql/badge.svg?branch=develop["Coverage Status", link="https://coveralls.io/github/vineey/archelix-rsql?branch=develop"]
image:https://api.codacy.com/project/badge/grade/b119ffa40c674a18850c31ec3878c044["Codacy code quality", link="https://www.codacy.com/app/vinetech416/archelix-rsql"]
image:https://maven-badges.herokuapp.com/maven-central/com.github.vineey/archelix-rsql/badge.svg["Maven Central", link="http://repo1.maven.org/maven2/com/github/vineey/archelix-rsql/"]
endif::env-github[]

_This library brings the convenience of SQL declarative nature to restful APIs in the form of RSQL
but without the danger of sql injection by using a typesafe mapping of allowed field paths defined
via integration with querydsl library. Like sql, it supports clauses such as select, filter, pagination 
and sorting that can easily be represented in http request parameters_.

_It primarily supports JPA model but if possible will strive to handle other kinds of database such as MongoDB.
This is a small project but at its heart is dedicated to maintain highly cohesive and modular components.
Contributions and suggestions are very much welcome and appreciated!_


== QueryDSL API
*  Filter - uses https://github.com/jirutka/rsql-parser[rsql-parser] library ast to convert filter string into its querydsl predicate equivalent
*  Select - converts a simple enumeration of field names separated by comma into its querydsl projection equivalent
*  Page - converts page parameters into its querydsl pagination equivalent
*  Sort - converts sort parameters into its querydsl sorting equivalent

== 1.0.0 Milestones

=== M1
Completes filter conversion to querydsl predicate.

=== M2
Completes sort and page conversion for rsql querydsl +
Tentative : Supports Mongodb filter, sort and page conversion.

=== M3
Completes select conversion to querydsl projections. +
Tentative : Supports Mongodb select conversion.

== 2.0.0 Milestones
*  Support for rsql conversion to https://github.com/jOOQ/jOOQ[JOOQ] Library
*  ?

== MAVEN

```xml
<dependency>
    <groupId>com.github.vineey</groupId>
    <artifactId>rsql-querydsl</artifactId>
    <version>1.0.0.M1</version>
</dependency>
```


[source,groovy]
[subs="attributes"]
----
dependencies {
    compile 'com.github.vineey:rsql-querydsl:1.0.0.M1'
  }
----


== DOCS

=== Filter API

Sample rsql-querydsl code

[source,java]
----

DefaultFilterParser filterParser = new DefaultFilterParser();

String rqlFilter = "employee.name == 'John'";

Map<String, Path> pathHashMap = ImmutableMap.<String, Path>builder()
                .put("employee.name", QEmployee.employee.name)
                .put("employee.age", QEmployee.employee.age)
                .put("employee.bday", QEmployee.employee.birthDate)
                .build();

Predicate predicate = filterParser.parse(rsqlFilter, withBuilderAndParam(new QuerydslFilterBuilder(), new QuerydslFilterParam()
                                                                             .setMapping(pathHashMap)));

  //or a shorter version
                                                                             
Predicate predicate = filterParser.parse(rsqlFilter, withMapping(pathHashMap));
                                                                             
----

You can now use this predicate in the JPAQuery of QEmployee or in the Spring Data JPA Repository.
